server:
  port: 8080
logging:
  config: classpath:logback-spring-dev.xml
  level:
    org:
      hibernate:
        SQL: DEBUG

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: movieProject
  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3305/board?useUnicode=true&characterEncoding=UTF-8

jwt:
  secret-key-source: ${JWT_SECRET_KEY}

